### ISSUE TITLE
Tests expect different response format than shown in previous lesson

### ISSUE THREAD

**Issue by ddeleon267** [learn-co-curriculum/python-p4-authenticating-users-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/219116?module_item_id=510937

### Concern

In the previous lessons, students are shown examples where views return the response with jsonify, e.g. 

```class Login(Resource):

    def post(self):
        user = User.query.filter(
            User.username == request.get_json()['username']
        ).first()

        session['user_id'] = user.id
        return jsonify(user.to_dict())
```

This returns a list, but if the students follow this pattern, they'll fail the lab tests because the tests expect a dictionary:

`- TypeError: list indices must be integers or slices, not str`

### Suggested Changes

Update the test expectations to check for a list, or add additional guidance for students so that they have a better understanding of what their views should return.

**Comment by professor-ben** [comment]
Hi Dominique,

Thanks for the report! There's a lot of goofy stuff going on with this lab right now, so I'm going to work out a few fixes in this and the previous lesson and push them up later today.

-Ben

**Comment by linda-seiter** [comment]
lesson updated to match lab expected result
